#!/usr/bin/env python3
from __future__ import annotations

import re
import sys
from pathlib import Path

from procurement_translation_by_name import BY_NAME

REPO_ROOT = Path(__file__).resolve().parent.parent
PROCUREMENT_OPTIONS_PATH = REPO_ROOT / "src/data/procurementOptions.ts"
OUTPUT_PATH = REPO_ROOT / "src/i18n/procurementItemTranslations.ts"
EXPECTED_COUNT = 261


def make_id(category: str, name: str, subcategory: str | None = None) -> str:
    parts = [category, subcategory, name]
    parts = [p for p in parts if p]
    s = "-".join(parts).lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def parse_procurement_items(source: str) -> list[tuple[str, str]]:
    start_marker = "export const PROCUREMENT_ITEMS"
    end_marker = "export const itemsByCategory"
    if start_marker not in source or end_marker not in source:
        raise RuntimeError("Could not locate PROCUREMENT_ITEMS section in procurementOptions.ts")

    section = source[source.index(start_marker) : source.index(end_marker)]
    triples = re.findall(r'item\(\s*"([^"]+)",\s*"([^"]+)",\s*"[^"]+"', section)
    items = [(make_id(cat, name), name) for cat, name in triples]
    if len(items) != EXPECTED_COUNT:
        raise RuntimeError(f"Expected {EXPECTED_COUNT} PROCUREMENT_ITEMS, found {len(items)}")
    return items


def ensure_no_latin(text: str) -> None:
    if re.search(r"[A-Za-z]", text):
        raise RuntimeError(f"Latin character found in translation: {text}")


def build_output(procurement_items: list[tuple[str, str]]) -> str:
    missing_names = sorted({name for _, name in procurement_items if name not in BY_NAME})
    if missing_names:
        print("Missing translations for these names:", file=sys.stderr)
        for name in missing_names:
            print(f" - {name}", file=sys.stderr)
        raise SystemExit(1)

    lines: list[str] = []
    lines.append('import type { Lang } from "./index";')
    lines.append("")
    lines.append("export const PROCUREMENT_ITEM_TRANSLATIONS: Record<string, Partial<Record<Lang, string>>> = {")

    translated = 0
    for item_id, english_name in procurement_items:
        hi, mr = BY_NAME[english_name]
        ensure_no_latin(hi)
        ensure_no_latin(mr)
        lines.append(f'  "{item_id}": {{ hi: "{hi}", mr: "{mr}" }},')
        translated += 1

    lines.append("};")
    lines.append("")
    lines.append(f"// Generated by scripts/build_procurement_translations.py ({translated} items)")
    return "\n".join(lines)


def main() -> int:
    source = PROCUREMENT_OPTIONS_PATH.read_text(encoding="utf-8")
    procurement_items = parse_procurement_items(source)
    output = build_output(procurement_items)
    OUTPUT_PATH.write_text(output, encoding="utf-8")

    print(f"Generated {OUTPUT_PATH.relative_to(REPO_ROOT)} with {len(procurement_items)} translated items.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
